parameters:
    database_driver: pdo_mysql
    database_host: 139.196.187.114
    database_port: 3306
    database_name: edusoho_demo
    database_user: eduxsy
    database_password: eduxsy20002016
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: zh_CN
    secret: cy8hefxjlc00ggk0scc4gw0wsw00ks0
    user_partner: none